### ISSUE TITLE
dynamically destroy and/or replace mask

### ISSUE THREAD

**Issue by leafling** [ViniChab/supermask.js#1]
I was looking at your masking solution and like how the tiny simple approach -- I like how the mask attribute is used on the inputs as well.

I was toying with it and trying to dynamically change the mask attribute with javascript to swap the mask for example, the code below will change the mask attribute for #d1 when the button is clicked, but it doesn't actually change the mask being applied. How would I achieve that?

`
<button onclick="document.getElementById('d1').setAttribute('mask', '999-999-999.99');_setupMaskEvents(maskFields, masks);">Change mask for Document #1</button><br />
`

`
    <span class="ml-2 badge badge-dark">Document #1</span>
    <input
      id="d1"
      mask="999.999.999-99"
      class="maskField"
      placeholder="999.999.999-99">
`

**Comment by ViniChab** [comment]
Dynamic mask change, huh

Well, this is a project I have because I was trying to solve some of my own problems, and that did not come to my mind, as it was not something I faced at work.

The thing is, we have functions that would be capable of rebuilding the mask, you would have to call:
```
    maskFields = _getMaskFields()
    masks = _getMasks(maskFields)
    _setupMaskEvents(maskFields, masks)
```

But I know, that's absolutely barbaric. So I created a small function called "rebuildMasks()". It's a public function, and you just need to call it as soon as you change the "mask" attribute. With that, it's going to update all the mask events.

That could be more performatic if you could pass a specific mask to rebuild, and that's a thing I'll add in the near future. But for now,  "rebuildMasks()" should do the job, as long as you change the "mask" attribute ;)

Also, a small problem I noticed is in case you want to change a mask while there's text on the input. In that case, there should be a function that would re-evaluate all the values and change the mask accordingly. That's quite an easy fix, that I'll also add in the near future.

Finally: That won't work on stackbitz, as you can't call functions from it's console (it kinda hides the JS from you). Just download the project, I also added a HTML file so people can toy with it in an actual browser.

Wish you the best, friend

**Comment by leafling** [comment]
You are right -- I was tinkering from within the stackbitz page and tried re-running those commands you listed, and as you mentioned those didn't work.  I'll just download and do my tinkering locally.  Thanks! :)
